apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: spark-k8s-operator-catalog
  # namespace: olm
spec:
  sourceType: grpc
  image: registry.cn-shanghai.aliyuncs.com/huagang/spark-k8s-operator-catalog:latest
  displayName: spark-k8s-operator-catalog
  publisher: zncdatadev
  updateStrategy:
    registryPoll:
      interval: 20m
