apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: spark-k8s-operator-catalog
  namespace: olm
spec:
  sourceType: grpc
  grpcPodConfig:
    securityContextConfig: restricted
  image: quay.io/zncdata/spark-k8s-operator-catalog:latest
  displayName: spark-k8s-operator-catalog
  publisher: zncdata-labs
  updateStrategy:
    registryPoll:
      interval: 5m
