apiVersion: spark.zncdata.dev/v1alpha1
kind: SparkHistoryServer
metadata:
  labels:
    app.kubernetes.io/name: sparkhistoryserver
    app.kubernetes.io/instance: sparkhistoryserver
    app.kubernetes.io/part-of: spark-k8s
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: spark-k8s-operator
  name: sparkhistoryserver-sample
spec:
  clusterOperation:
    stopped: false
  clusterConfig:
    listenerClass: external-unstable
  sparkHistory:
    config:
      resources:
        cpu:
          min: 100m
          max: 200m
        memory:
          limit: 512Mi
    roleGroups:
      default:
        replicas: 1
        config:
          gracefulShutdownTimeout: 10s
          logging:
            sparkHistory:
              console:
                level: "INFO"
          resources:
            cpu:
              min: 300m
              max: 400m
            memory:
              limit: 612Mi
