apiVersion: stack.zncdata.net/v1alpha1
kind: SparkHistoryServer
metadata:
  labels:
    app.kubernetes.io/name: sparkhistoryserver
    app.kubernetes.io/instance: sparkhistoryserver
    app.kubernetes.io/part-of: spark-k8s
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: spark-k8s-operator
  name: sparkhistoryserver-sample
spec:
  roleConfig:
    eventLog:
      enabled: true
      mountMode: pvc
      dir: /tmp/spark-events
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
    replicas: 3
    config:
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
    image:
      repository: bitnami/spark
      tag: 3.1.1
      pullPolicy: IfNotPresent
    service:
      port: 18080
      type: ClusterIP
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: /
      host: spark-history-server.example.com
  roleGroups:
    default:
      replicas: 1
      config:
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
      matchLabels:
          app: default
      ingress:
        enabled: false
    large:
        replicas: 2
        config:
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
        matchLabels:
            app: foo