# e2e test

name: e2e-test

on: ['push', 'pull_request']

jobs:
  chainsaw-test:
    name: Chainsaw Test
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        k8s-version: ['1.26.14', '1.27.11']
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: false

    - name: Create KinD cluster
      run: make kind-create ENVTEST_K8S_VERSION=${{ matrix.k8s-version}}
    - name: Chainsaw test setup
      run: make chainsaw-setup
    - name: Test with Chainsaw
      run: make chainsaw-test
